### ISSUE TITLE
Tutorial accessiblity

### ISSUE THREAD

**Issue by Roy-Lam** [CelynChew/CITS3403#12]
Currently the tutorial page can be accessed only through chatroom. I suggest that the tutorial page is accessible through log in page and chatroom and cutting out user log in session (if accessed through chatroom). The tutorial redirecting buttons should only go back to log in page. (This action doesn't count as Logging out, instead the action of going to tutorial from chatroom should be equal to quiting the log in session)

**Comment by CelynChew** [comment]
A back button is added to the tutorial page and made it so that users will go back to their previous page. I did remove the `@login_required` for the route. Don't foresee any issue because if users go to the tutorial page through the login page, they haven't logged in so they would not be able to access the chatroom through the tutorial page.

Let me know what you think. Thank you

**Comment by Roy-Lam** [comment]
When returning to chatroom from tutorial through the back button will still allow access to the previous logged in user in the chatroom. This can either be left alone (issue ready to be closed) or make sure the user returns to login page when leaving tutorial no matter how the page is accessed.

**Comment by Roy-Lam** [comment]
As returning to chatroom through tutorial is considered as a quality of life feature, this issue is resolved and will be closed.

**Comment by Roy-Lam** [comment]
Closing issue
